package com.telesure.gittest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test1Obj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("age")
	private java.lang.String age;

	@org.kie.api.definition.type.Label(value = "status")
	private java.lang.String status;

	public test1Obj() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAge() {
		return this.age;
	}

	public void setAge(java.lang.String age) {
		this.age = age;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public test1Obj(java.lang.String name, java.lang.String age,
			java.lang.String status) {
		this.name = name;
		this.age = age;
		this.status = status;
	}

}