package com.telesure.gittest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test1Obj implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public test1Obj() {
    }




}